# Generated by Django 3.0.3 on 2020-02-15 12:52

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('sport_field', models.CharField(choices=[('A', 'Aerobic'), ('F', 'Fitness'), ('T', 'TRX'), ('B', 'Bodybuilding'), ('P', 'Physic'), ('C', 'Crossfit')], max_length=1)),
                ('days_of_week', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Saturday'), ('2', 'Sunday'), ('3', 'Monday'), ('4', 'Tuesday'), ('5', 'Wednesday'), ('6', 'Thursday'), ('7', 'Friday')], max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Person')),
                ('salary', models.BigIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            bases=('users.person',),
        ),
        migrations.CreateModel(
            name='Athelte',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Person')),
                ('last_payment', models.DateField()),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Coach')),
            ],
            bases=('users.person',),
        ),
    ]
