# Generated by Django 3.0.3 on 2020-02-25 13:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=28, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Person')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTradeOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('amount', models.BigIntegerField()),
                ('code', models.CharField(default=b'df2d0a4ce2cf62350cad', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('sport_field', models.CharField(choices=[('A', 'Aerobic'), ('F', 'Fitness'), ('T', 'TRX'), ('B', 'Bodybuilding'), ('P', 'Physic'), ('C', 'Crossfit')], max_length=1, null=True)),
                ('days_of_week', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Saturday'), ('2', 'Sunday'), ('3', 'Monday'), ('4', 'Tuesday'), ('5', 'Wednesday'), ('6', 'Thursday'), ('7', 'Friday')], max_length=13, null=True)),
                ('salary', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('sport_field', models.CharField(choices=[('A', 'Aerobic'), ('F', 'Fitness'), ('T', 'TRX'), ('B', 'Bodybuilding'), ('P', 'Physic'), ('C', 'Crossfit')], max_length=1, null=True)),
                ('days_of_week', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Saturday'), ('2', 'Sunday'), ('3', 'Monday'), ('4', 'Tuesday'), ('5', 'Wednesday'), ('6', 'Thursday'), ('7', 'Friday')], max_length=13, null=True)),
                ('last_payment', models.DateField(default=django.utils.timezone.now)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Coach')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
