# Generated by Django 3.0.3 on 2020-04-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.AddField(
            model_name='coach',
            name='last_income',
            field=models.ManyToManyField(to='finance.Income'),
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='last_payment',
        ),
        migrations.AddField(
            model_name='athlete',
            name='last_payment',
            field=models.ManyToManyField(to='finance.Expense'),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
