# Generated by Django 3.0.3 on 2020-04-05 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('users', '0002_auto_20200405_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='last_payment',
        ),
        migrations.AddField(
            model_name='athlete',
            name='last_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Expense'),
        ),
        migrations.RemoveField(
            model_name='coach',
            name='last_income',
        ),
        migrations.AddField(
            model_name='coach',
            name='last_income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Income'),
        ),
    ]
