# Generated by Django 3.0.3 on 2020-02-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200215_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Athelte',
            new_name='Athlete',
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Person')),
            ],
        ),
    ]
