# Generated by Django 3.0.3 on 2020-02-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200217_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='sex',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
