# Generated by Django 3.0.3 on 2020-02-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200227_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_trainer', to='users.Person'),
        ),
    ]
