# Generated by Django 3.0.3 on 2020-04-05 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('users', '0003_auto_20200405_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='last_payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Expense'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='last_income',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Income'),
        ),
    ]
