# Generated by Django 3.0.3 on 2020-04-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200405_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='last_payment',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='last_income',
        ),
        migrations.AddField(
            model_name='athlete',
            name='last_transaction',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='last_transaction',
            field=models.DateField(auto_now=True),
        ),
    ]
