# Generated by Django 3.0.3 on 2020-04-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200405_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='salary',
        ),
        migrations.AddField(
            model_name='athlete',
            name='transaction_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='transaction_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
