# Generated by Django 3.0.3 on 2020-02-28 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200228_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='code',
            field=models.CharField(default=users.models.FinancialTradeOff.random_code, max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 20, 34, 19, 218792), null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Person'),
        ),
        migrations.AddField(
            model_name='income',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='code',
            field=models.CharField(default=users.models.FinancialTradeOff.random_code, max_length=10),
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 20, 34, 19, 218792), null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Person'),
        ),
        migrations.DeleteModel(
            name='FinancialTradeOff',
        ),
    ]
