# Generated by Django 3.0.3 on 2020-02-23 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_person_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='coach',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='person',
            name='sport_field',
        ),
        migrations.AddField(
            model_name='coach',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Saturday'), ('2', 'Sunday'), ('3', 'Monday'), ('4', 'Tuesday'), ('5', 'Wednesday'), ('6', 'Thursday'), ('7', 'Friday')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='sport_field',
            field=models.CharField(choices=[('A', 'Aerobic'), ('F', 'Fitness'), ('T', 'TRX'), ('B', 'Bodybuilding'), ('P', 'Physic'), ('C', 'Crossfit')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_payment',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='FinancialTradeOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('amount', models.BigIntegerField()),
                ('code', models.CharField(default=b'c96d9fd7b81314cc058b', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Person')),
            ],
        ),
    ]
