# Generated by Django 3.0.3 on 2020-04-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200406_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='last_transaction',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='last_transaction',
            field=models.DateField(null=True),
        ),
    ]
