# Generated by Django 3.0.3 on 2020-02-25 07:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200223_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Saturday'), ('2', 'Sunday'), ('3', 'Monday'), ('4', 'Tuesday'), ('5', 'Wednesday'), ('6', 'Thursday'), ('7', 'Friday')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sport_field',
            field=models.CharField(choices=[('A', 'Aerobic'), ('F', 'Fitness'), ('T', 'TRX'), ('B', 'Bodybuilding'), ('P', 'Physic'), ('C', 'Crossfit')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='financialtradeoff',
            name='code',
            field=models.CharField(default=b'981ac5c622ad8fa3eb1d', max_length=10),
        ),
    ]
