# Generated by Django 3.0.3 on 2020-02-28 19:22

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200228_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='code',
            field=models.CharField(default=users.utils.random_code, max_length=24),
        ),
        migrations.AlterField(
            model_name='income',
            name='code',
            field=models.CharField(default=users.utils.random_code, max_length=24),
        ),
    ]
