# Generated by Django 3.0.3 on 2020-04-21 12:59

from django.db import migrations, models
import utils_module.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200413_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='code',
            field=models.CharField(default=utils_module.utils.random_code, max_length=28, null=True),
        ),
    ]
