# Generated by Django 3.0.3 on 2020-03-01 09:34

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200301_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='code',
            field=models.CharField(default=users.utils.random_code, max_length=48),
        ),
        migrations.AlterField(
            model_name='income',
            name='code',
            field=models.CharField(default=users.utils.random_code, max_length=48),
        ),
    ]
