# Generated by Django 3.0.3 on 2020-03-12 16:40

from django.db import migrations, models
import django.utils.timezone
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_person_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(default=users.utils.random_code, max_length=28, null=True),
        ),
    ]
