# Generated by Django 3.0.3 on 2020-03-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200312_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=9)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='days_of_week',
        ),
    ]
