# Generated by Django 3.0.3 on 2020-03-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200315_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='days_of_week',
            field=models.ManyToManyField(null=True, to='users.Day'),
        ),
        migrations.AddField(
            model_name='coach',
            name='days_of_week',
            field=models.ManyToManyField(null=True, to='users.Day'),
        ),
    ]
