# Generated by Django 3.0.3 on 2020-03-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200315_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='days_of_week',
            field=models.ManyToManyField(to='users.Day'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='days_of_week',
            field=models.ManyToManyField(to='users.Day'),
        ),
    ]
