# Generated by Django 3.0.3 on 2020-03-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200315_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='trainer',
        ),
    ]
