# Generated by Django 3.0.3 on 2020-03-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_athlete_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_trainer', to='users.Coach'),
        ),
    ]
