# Generated by Django 3.0.3 on 2020-03-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_athlete_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
