# Generated by Django 3.0.3 on 2020-03-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200326_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='salary',
            field=models.BigIntegerField(default=1500000),
        ),
    ]
