# Generated by Django 3.0.3 on 2020-03-26 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200326_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='days_of_week',
        ),
    ]
