# Generated by Django 3.0.3 on 2020-03-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200326_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='days_of_week',
            field=models.ManyToManyField(to='users.Day'),
        ),
        migrations.AddField(
            model_name='coach',
            name='days_of_week',
            field=models.ManyToManyField(to='users.Day'),
        ),
    ]
